<?php
/**
 * CheckResult
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Permify API
 *
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.5.4
 * Contact: hello@permify.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Permify\Model;
use \Permify\ObjectSerializer;

/**
 * CheckResult Class Doc Comment
 *
 * @category Class
 * @description Enumerates results of a check operation.   - CHECK_RESULT_ALLOWED: Represents a successful check (the check allowed the operation).  - CHECK_RESULT_DENIED: Represents a failed check (the check denied the operation).
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CheckResult
{
    /**
     * Possible values of this enum
     */
    public const ALLOWED = 'CHECK_RESULT_ALLOWED';

    public const DENIED = 'CHECK_RESULT_DENIED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ALLOWED,
            self::DENIED
        ];
    }
}


