<?php
/**
 * EntityDefinitionReference
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Permify API
 *
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.5.4
 * Contact: hello@permify.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Permify\Model;
use \Permify\ObjectSerializer;

/**
 * EntityDefinitionReference Class Doc Comment
 *
 * @category Class
 * @description The Reference enum specifies whether a name pertains to a relation, permission, or attribute.   - REFERENCE_RELATION: Indicates that the name refers to a relation.  - REFERENCE_PERMISSION: Indicates that the name refers to a permission.  - REFERENCE_ATTRIBUTE: Indicates that the name refers to an attribute.
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EntityDefinitionReference
{
    /**
     * Possible values of this enum
     */
    public const RELATION = 'REFERENCE_RELATION';

    public const PERMISSION = 'REFERENCE_PERMISSION';

    public const ATTRIBUTE = 'REFERENCE_ATTRIBUTE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::RELATION,
            self::PERMISSION,
            self::ATTRIBUTE
        ];
    }
}


