<?php
/**
 * ExpandTreeNodeOperation
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Permify API
 *
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.5.4
 * Contact: hello@permify.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Permify\Model;
use \Permify\ObjectSerializer;

/**
 * ExpandTreeNodeOperation Class Doc Comment
 *
 * @category Class
 * @description Operation is an enum representing the type of operation to be applied on the tree node.
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ExpandTreeNodeOperation
{
    /**
     * Possible values of this enum
     */
    public const UNION = 'OPERATION_UNION';

    public const INTERSECTION = 'OPERATION_INTERSECTION';

    public const EXCLUSION = 'OPERATION_EXCLUSION';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNION,
            self::INTERSECTION,
            self::EXCLUSION
        ];
    }
}


