<?php
/**
 * Leaf
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Permify API
 *
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.5.4
 * Contact: hello@permify.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Permify\Model;

use \ArrayAccess;
use \Permify\ObjectSerializer;

/**
 * Leaf Class Doc Comment
 *
 * @category Class
 * @description Leaf represents a leaf node in the permission tree.
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Leaf implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Leaf';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'computed_user_set' => '\Permify\Model\ComputedUserSet',
        'tuple_to_user_set' => '\Permify\Model\TupleToUserSet',
        'computed_attribute' => '\Permify\Model\ComputedAttribute',
        'call' => '\Permify\Model\V1Call'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'computed_user_set' => null,
        'tuple_to_user_set' => null,
        'computed_attribute' => null,
        'call' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'computed_user_set' => false,
        'tuple_to_user_set' => false,
        'computed_attribute' => false,
        'call' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'computed_user_set' => 'computedUserSet',
        'tuple_to_user_set' => 'tupleToUserSet',
        'computed_attribute' => 'computedAttribute',
        'call' => 'call'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'computed_user_set' => 'setComputedUserSet',
        'tuple_to_user_set' => 'setTupleToUserSet',
        'computed_attribute' => 'setComputedAttribute',
        'call' => 'setCall'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'computed_user_set' => 'getComputedUserSet',
        'tuple_to_user_set' => 'getTupleToUserSet',
        'computed_attribute' => 'getComputedAttribute',
        'call' => 'getCall'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('computed_user_set', $data ?? [], null);
        $this->setIfExists('tuple_to_user_set', $data ?? [], null);
        $this->setIfExists('computed_attribute', $data ?? [], null);
        $this->setIfExists('call', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets computed_user_set
     *
     * @return \Permify\Model\ComputedUserSet|null
     */
    public function getComputedUserSet()
    {
        return $this->container['computed_user_set'];
    }

    /**
     * Sets computed_user_set
     *
     * @param \Permify\Model\ComputedUserSet|null $computed_user_set computed_user_set
     *
     * @return self
     */
    public function setComputedUserSet($computed_user_set)
    {
        if (is_null($computed_user_set)) {
            throw new \InvalidArgumentException('non-nullable computed_user_set cannot be null');
        }
        $this->container['computed_user_set'] = $computed_user_set;

        return $this;
    }

    /**
     * Gets tuple_to_user_set
     *
     * @return \Permify\Model\TupleToUserSet|null
     */
    public function getTupleToUserSet()
    {
        return $this->container['tuple_to_user_set'];
    }

    /**
     * Sets tuple_to_user_set
     *
     * @param \Permify\Model\TupleToUserSet|null $tuple_to_user_set tuple_to_user_set
     *
     * @return self
     */
    public function setTupleToUserSet($tuple_to_user_set)
    {
        if (is_null($tuple_to_user_set)) {
            throw new \InvalidArgumentException('non-nullable tuple_to_user_set cannot be null');
        }
        $this->container['tuple_to_user_set'] = $tuple_to_user_set;

        return $this;
    }

    /**
     * Gets computed_attribute
     *
     * @return \Permify\Model\ComputedAttribute|null
     */
    public function getComputedAttribute()
    {
        return $this->container['computed_attribute'];
    }

    /**
     * Sets computed_attribute
     *
     * @param \Permify\Model\ComputedAttribute|null $computed_attribute computed_attribute
     *
     * @return self
     */
    public function setComputedAttribute($computed_attribute)
    {
        if (is_null($computed_attribute)) {
            throw new \InvalidArgumentException('non-nullable computed_attribute cannot be null');
        }
        $this->container['computed_attribute'] = $computed_attribute;

        return $this;
    }

    /**
     * Gets call
     *
     * @return \Permify\Model\V1Call|null
     */
    public function getCall()
    {
        return $this->container['call'];
    }

    /**
     * Sets call
     *
     * @param \Permify\Model\V1Call|null $call call
     *
     * @return self
     */
    public function setCall($call)
    {
        if (is_null($call)) {
            throw new \InvalidArgumentException('non-nullable call cannot be null');
        }
        $this->container['call'] = $call;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


