<?php
/**
 * WellKnownType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Permify API
 *
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.5.4
 * Contact: hello@permify.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Permify\Model;
use \Permify\ObjectSerializer;

/**
 * WellKnownType Class Doc Comment
 *
 * @category Class
 * @description Well-known protobuf types treated with first-class support in CEL.   - ANY: Well-known protobuf.Any type.  Any types are a polymorphic message type. During type-checking they are treated like &#x60;DYN&#x60; types, but at runtime they are resolved to a specific message type specified at evaluation time.  - TIMESTAMP: Well-known protobuf.Timestamp type, internally referenced as &#x60;timestamp&#x60;.  - DURATION: Well-known protobuf.Duration type, internally referenced as &#x60;duration&#x60;.
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WellKnownType
{
    /**
     * Possible values of this enum
     */
    public const ANY = 'ANY';

    public const TIMESTAMP = 'TIMESTAMP';

    public const DURATION = 'DURATION';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ANY,
            self::TIMESTAMP,
            self::DURATION
        ];
    }
}


