<?php
/**
 * AttributeType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Permify API
 *
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.5.4
 * Contact: hello@permify.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Permify\Model;
use \Permify\ObjectSerializer;

/**
 * AttributeType Class Doc Comment
 *
 * @category Class
 * @description Enumerates the types of attribute.   - ATTRIBUTE_TYPE_BOOLEAN: A boolean attribute type.  - ATTRIBUTE_TYPE_BOOLEAN_ARRAY: A boolean array attribute type.  - ATTRIBUTE_TYPE_STRING: A string attribute type.  - ATTRIBUTE_TYPE_STRING_ARRAY: A string array attribute type.  - ATTRIBUTE_TYPE_INTEGER: An integer attribute type.  - ATTRIBUTE_TYPE_INTEGER_ARRAY: An integer array attribute type.  - ATTRIBUTE_TYPE_DOUBLE: A double attribute type.  - ATTRIBUTE_TYPE_DOUBLE_ARRAY: A double array attribute type.
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AttributeType
{
    /**
     * Possible values of this enum
     */
    public const BOOLEAN = 'ATTRIBUTE_TYPE_BOOLEAN';

    public const BOOLEAN_ARRAY = 'ATTRIBUTE_TYPE_BOOLEAN_ARRAY';

    public const STRING = 'ATTRIBUTE_TYPE_STRING';

    public const STRING_ARRAY = 'ATTRIBUTE_TYPE_STRING_ARRAY';

    public const INTEGER = 'ATTRIBUTE_TYPE_INTEGER';

    public const INTEGER_ARRAY = 'ATTRIBUTE_TYPE_INTEGER_ARRAY';

    public const DOUBLE = 'ATTRIBUTE_TYPE_DOUBLE';

    public const DOUBLE_ARRAY = 'ATTRIBUTE_TYPE_DOUBLE_ARRAY';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BOOLEAN,
            self::BOOLEAN_ARRAY,
            self::STRING,
            self::STRING_ARRAY,
            self::INTEGER,
            self::INTEGER_ARRAY,
            self::DOUBLE,
            self::DOUBLE_ARRAY
        ];
    }
}


