<?php
/**
 * CheckedExpr
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Permify API
 *
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.5.4
 * Contact: hello@permify.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Permify\Model;

use \ArrayAccess;
use \Permify\ObjectSerializer;

/**
 * CheckedExpr Class Doc Comment
 *
 * @category Class
 * @description A CEL expression which has been successfully type checked.
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CheckedExpr implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CheckedExpr';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'reference_map' => 'array<string,\Permify\Model\V1alpha1Reference>',
        'type_map' => 'array<string,\Permify\Model\V1alpha1Type>',
        'source_info' => '\Permify\Model\SourceInfo',
        'expr_version' => 'string',
        'expr' => '\Permify\Model\Expr'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'reference_map' => null,
        'type_map' => null,
        'source_info' => null,
        'expr_version' => null,
        'expr' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'reference_map' => false,
        'type_map' => false,
        'source_info' => false,
        'expr_version' => false,
        'expr' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'reference_map' => 'referenceMap',
        'type_map' => 'typeMap',
        'source_info' => 'sourceInfo',
        'expr_version' => 'exprVersion',
        'expr' => 'expr'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'reference_map' => 'setReferenceMap',
        'type_map' => 'setTypeMap',
        'source_info' => 'setSourceInfo',
        'expr_version' => 'setExprVersion',
        'expr' => 'setExpr'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'reference_map' => 'getReferenceMap',
        'type_map' => 'getTypeMap',
        'source_info' => 'getSourceInfo',
        'expr_version' => 'getExprVersion',
        'expr' => 'getExpr'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('reference_map', $data ?? [], null);
        $this->setIfExists('type_map', $data ?? [], null);
        $this->setIfExists('source_info', $data ?? [], null);
        $this->setIfExists('expr_version', $data ?? [], null);
        $this->setIfExists('expr', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets reference_map
     *
     * @return array<string,\Permify\Model\V1alpha1Reference>|null
     */
    public function getReferenceMap()
    {
        return $this->container['reference_map'];
    }

    /**
     * Sets reference_map
     *
     * @param array<string,\Permify\Model\V1alpha1Reference>|null $reference_map A map from expression ids to resolved references.  The following entries are in this table:  - An Ident or Select expression is represented here if it resolves to a   declaration. For instance, if `a.b.c` is represented by   `select(select(id(a), b), c)`, and `a.b` resolves to a declaration,   while `c` is a field selection, then the reference is attached to the   nested select expression (but not to the id or or the outer select).   In turn, if `a` resolves to a declaration and `b.c` are field selections,   the reference is attached to the ident expression. - Every Call expression has an entry here, identifying the function being   called. - Every CreateStruct expression for a message has an entry, identifying   the message.
     *
     * @return self
     */
    public function setReferenceMap($reference_map)
    {
        if (is_null($reference_map)) {
            throw new \InvalidArgumentException('non-nullable reference_map cannot be null');
        }
        $this->container['reference_map'] = $reference_map;

        return $this;
    }

    /**
     * Gets type_map
     *
     * @return array<string,\Permify\Model\V1alpha1Type>|null
     */
    public function getTypeMap()
    {
        return $this->container['type_map'];
    }

    /**
     * Sets type_map
     *
     * @param array<string,\Permify\Model\V1alpha1Type>|null $type_map A map from expression ids to types.  Every expression node which has a type different than DYN has a mapping here. If an expression has type DYN, it is omitted from this map to save space.
     *
     * @return self
     */
    public function setTypeMap($type_map)
    {
        if (is_null($type_map)) {
            throw new \InvalidArgumentException('non-nullable type_map cannot be null');
        }
        $this->container['type_map'] = $type_map;

        return $this;
    }

    /**
     * Gets source_info
     *
     * @return \Permify\Model\SourceInfo|null
     */
    public function getSourceInfo()
    {
        return $this->container['source_info'];
    }

    /**
     * Sets source_info
     *
     * @param \Permify\Model\SourceInfo|null $source_info source_info
     *
     * @return self
     */
    public function setSourceInfo($source_info)
    {
        if (is_null($source_info)) {
            throw new \InvalidArgumentException('non-nullable source_info cannot be null');
        }
        $this->container['source_info'] = $source_info;

        return $this;
    }

    /**
     * Gets expr_version
     *
     * @return string|null
     */
    public function getExprVersion()
    {
        return $this->container['expr_version'];
    }

    /**
     * Sets expr_version
     *
     * @param string|null $expr_version The expr version indicates the major / minor version number of the `expr` representation.  The most common reason for a version change will be to indicate to the CEL runtimes that transformations have been performed on the expr during static analysis. In some cases, this will save the runtime the work of applying the same or similar transformations prior to evaluation.
     *
     * @return self
     */
    public function setExprVersion($expr_version)
    {
        if (is_null($expr_version)) {
            throw new \InvalidArgumentException('non-nullable expr_version cannot be null');
        }
        $this->container['expr_version'] = $expr_version;

        return $this;
    }

    /**
     * Gets expr
     *
     * @return \Permify\Model\Expr|null
     */
    public function getExpr()
    {
        return $this->container['expr'];
    }

    /**
     * Sets expr
     *
     * @param \Permify\Model\Expr|null $expr expr
     *
     * @return self
     */
    public function setExpr($expr)
    {
        if (is_null($expr)) {
            throw new \InvalidArgumentException('non-nullable expr cannot be null');
        }
        $this->container['expr'] = $expr;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


