<?php
/**
 * Component
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Permify API
 *
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.5.4
 * Contact: hello@permify.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Permify\Model;
use \Permify\ObjectSerializer;

/**
 * Component Class Doc Comment
 *
 * @category Class
 * @description CEL component specifier.   - COMPONENT_PARSER: Parser. Converts a CEL string to an AST.  - COMPONENT_TYPE_CHECKER: Type checker. Checks that references in an AST are defined and types agree.  - COMPONENT_RUNTIME: Runtime. Evaluates a parsed and optionally checked CEL AST against a context.
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Component
{
    /**
     * Possible values of this enum
     */
    public const PARSER = 'COMPONENT_PARSER';

    public const TYPE_CHECKER = 'COMPONENT_TYPE_CHECKER';

    public const RUNTIME = 'COMPONENT_RUNTIME';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PARSER,
            self::TYPE_CHECKER,
            self::RUNTIME
        ];
    }
}


