<?php
/**
 * Constant
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Permify API
 *
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.5.4
 * Contact: hello@permify.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Permify\Model;

use \ArrayAccess;
use \Permify\ObjectSerializer;

/**
 * Constant Class Doc Comment
 *
 * @category Class
 * @description Represents a primitive literal.  Named &#39;Constant&#39; here for backwards compatibility.  This is similar as the primitives supported in the well-known type &#x60;google.protobuf.Value&#x60;, but richer so it can represent CEL&#39;s full range of primitives.  Lists and structs are not included as constants as these aggregate types may contain [Expr][google.api.expr.v1alpha1.Expr] elements which require evaluation and are thus not constant.  Examples of literals include: &#x60;\&quot;hello\&quot;&#x60;, &#x60;b&#39;bytes&#39;&#x60;, &#x60;1u&#x60;, &#x60;4.2&#x60;, &#x60;-2&#x60;, &#x60;true&#x60;, &#x60;null&#x60;.
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Constant implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Constant';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'null_value' => 'string',
        'bool_value' => 'bool',
        'int64_value' => 'string',
        'uint64_value' => 'string',
        'double_value' => 'float',
        'string_value' => 'string',
        'bytes_value' => 'string',
        'duration_value' => 'string',
        'timestamp_value' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'null_value' => null,
        'bool_value' => null,
        'int64_value' => 'int64',
        'uint64_value' => 'uint64',
        'double_value' => 'double',
        'string_value' => null,
        'bytes_value' => 'byte',
        'duration_value' => null,
        'timestamp_value' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'null_value' => false,
        'bool_value' => false,
        'int64_value' => false,
        'uint64_value' => false,
        'double_value' => false,
        'string_value' => false,
        'bytes_value' => false,
        'duration_value' => false,
        'timestamp_value' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'null_value' => 'nullValue',
        'bool_value' => 'boolValue',
        'int64_value' => 'int64Value',
        'uint64_value' => 'uint64Value',
        'double_value' => 'doubleValue',
        'string_value' => 'stringValue',
        'bytes_value' => 'bytesValue',
        'duration_value' => 'durationValue',
        'timestamp_value' => 'timestampValue'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'null_value' => 'setNullValue',
        'bool_value' => 'setBoolValue',
        'int64_value' => 'setInt64Value',
        'uint64_value' => 'setUint64Value',
        'double_value' => 'setDoubleValue',
        'string_value' => 'setStringValue',
        'bytes_value' => 'setBytesValue',
        'duration_value' => 'setDurationValue',
        'timestamp_value' => 'setTimestampValue'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'null_value' => 'getNullValue',
        'bool_value' => 'getBoolValue',
        'int64_value' => 'getInt64Value',
        'uint64_value' => 'getUint64Value',
        'double_value' => 'getDoubleValue',
        'string_value' => 'getStringValue',
        'bytes_value' => 'getBytesValue',
        'duration_value' => 'getDurationValue',
        'timestamp_value' => 'getTimestampValue'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('null_value', $data ?? [], null);
        $this->setIfExists('bool_value', $data ?? [], null);
        $this->setIfExists('int64_value', $data ?? [], null);
        $this->setIfExists('uint64_value', $data ?? [], null);
        $this->setIfExists('double_value', $data ?? [], null);
        $this->setIfExists('string_value', $data ?? [], null);
        $this->setIfExists('bytes_value', $data ?? [], null);
        $this->setIfExists('duration_value', $data ?? [], null);
        $this->setIfExists('timestamp_value', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['bytes_value']) && !preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", $this->container['bytes_value'])) {
            $invalidProperties[] = "invalid value for 'bytes_value', must be conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets null_value
     *
     * @return string|null
     */
    public function getNullValue()
    {
        return $this->container['null_value'];
    }

    /**
     * Sets null_value
     *
     * @param string|null $null_value null value.
     *
     * @return self
     */
    public function setNullValue($null_value)
    {
        if (is_null($null_value)) {
            throw new \InvalidArgumentException('non-nullable null_value cannot be null');
        }
        $this->container['null_value'] = $null_value;

        return $this;
    }

    /**
     * Gets bool_value
     *
     * @return bool|null
     */
    public function getBoolValue()
    {
        return $this->container['bool_value'];
    }

    /**
     * Sets bool_value
     *
     * @param bool|null $bool_value boolean value.
     *
     * @return self
     */
    public function setBoolValue($bool_value)
    {
        if (is_null($bool_value)) {
            throw new \InvalidArgumentException('non-nullable bool_value cannot be null');
        }
        $this->container['bool_value'] = $bool_value;

        return $this;
    }

    /**
     * Gets int64_value
     *
     * @return string|null
     */
    public function getInt64Value()
    {
        return $this->container['int64_value'];
    }

    /**
     * Sets int64_value
     *
     * @param string|null $int64_value int64 value.
     *
     * @return self
     */
    public function setInt64Value($int64_value)
    {
        if (is_null($int64_value)) {
            throw new \InvalidArgumentException('non-nullable int64_value cannot be null');
        }
        $this->container['int64_value'] = $int64_value;

        return $this;
    }

    /**
     * Gets uint64_value
     *
     * @return string|null
     */
    public function getUint64Value()
    {
        return $this->container['uint64_value'];
    }

    /**
     * Sets uint64_value
     *
     * @param string|null $uint64_value uint64 value.
     *
     * @return self
     */
    public function setUint64Value($uint64_value)
    {
        if (is_null($uint64_value)) {
            throw new \InvalidArgumentException('non-nullable uint64_value cannot be null');
        }
        $this->container['uint64_value'] = $uint64_value;

        return $this;
    }

    /**
     * Gets double_value
     *
     * @return float|null
     */
    public function getDoubleValue()
    {
        return $this->container['double_value'];
    }

    /**
     * Sets double_value
     *
     * @param float|null $double_value double value.
     *
     * @return self
     */
    public function setDoubleValue($double_value)
    {
        if (is_null($double_value)) {
            throw new \InvalidArgumentException('non-nullable double_value cannot be null');
        }
        $this->container['double_value'] = $double_value;

        return $this;
    }

    /**
     * Gets string_value
     *
     * @return string|null
     */
    public function getStringValue()
    {
        return $this->container['string_value'];
    }

    /**
     * Sets string_value
     *
     * @param string|null $string_value string value.
     *
     * @return self
     */
    public function setStringValue($string_value)
    {
        if (is_null($string_value)) {
            throw new \InvalidArgumentException('non-nullable string_value cannot be null');
        }
        $this->container['string_value'] = $string_value;

        return $this;
    }

    /**
     * Gets bytes_value
     *
     * @return string|null
     */
    public function getBytesValue()
    {
        return $this->container['bytes_value'];
    }

    /**
     * Sets bytes_value
     *
     * @param string|null $bytes_value bytes value.
     *
     * @return self
     */
    public function setBytesValue($bytes_value)
    {
        if (is_null($bytes_value)) {
            throw new \InvalidArgumentException('non-nullable bytes_value cannot be null');
        }

        if ((!preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", ObjectSerializer::toString($bytes_value)))) {
            throw new \InvalidArgumentException("invalid value for \$bytes_value when calling Constant., must conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.");
        }

        $this->container['bytes_value'] = $bytes_value;

        return $this;
    }

    /**
     * Gets duration_value
     *
     * @return string|null
     */
    public function getDurationValue()
    {
        return $this->container['duration_value'];
    }

    /**
     * Sets duration_value
     *
     * @param string|null $duration_value protobuf.Duration value.  Deprecated: duration is no longer considered a builtin cel type.
     *
     * @return self
     */
    public function setDurationValue($duration_value)
    {
        if (is_null($duration_value)) {
            throw new \InvalidArgumentException('non-nullable duration_value cannot be null');
        }
        $this->container['duration_value'] = $duration_value;

        return $this;
    }

    /**
     * Gets timestamp_value
     *
     * @return \DateTime|null
     */
    public function getTimestampValue()
    {
        return $this->container['timestamp_value'];
    }

    /**
     * Sets timestamp_value
     *
     * @param \DateTime|null $timestamp_value protobuf.Timestamp value.  Deprecated: timestamp is no longer considered a builtin cel type.
     *
     * @return self
     */
    public function setTimestampValue($timestamp_value)
    {
        if (is_null($timestamp_value)) {
            throw new \InvalidArgumentException('non-nullable timestamp_value cannot be null');
        }
        $this->container['timestamp_value'] = $timestamp_value;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


