<?php
/**
 * Expr
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Permify API
 *
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.5.4
 * Contact: hello@permify.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Permify\Model;

use \ArrayAccess;
use \Permify\ObjectSerializer;

/**
 * Expr Class Doc Comment
 *
 * @category Class
 * @description An abstract representation of a common expression.  Expressions are abstractly represented as a collection of identifiers, select statements, function calls, literals, and comprehensions. All operators with the exception of the &#39;.&#39; operator are modelled as function calls. This makes it easy to represent new operators into the existing AST.  All references within expressions must resolve to a [Decl][google.api.expr.v1alpha1.Decl] provided at type-check for an expression to be valid. A reference may either be a bare identifier &#x60;name&#x60; or a qualified identifier &#x60;google.api.name&#x60;. References may either refer to a value or a function declaration.  For example, the expression &#x60;google.api.name.startsWith(&#39;expr&#39;)&#x60; references the declaration &#x60;google.api.name&#x60; within a [Expr.Select][google.api.expr.v1alpha1.Expr.Select] expression, and the function declaration &#x60;startsWith&#x60;.
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Expr implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Expr';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'const_expr' => '\Permify\Model\Constant',
        'ident_expr' => '\Permify\Model\Ident',
        'select_expr' => '\Permify\Model\Select',
        'call_expr' => '\Permify\Model\ExprCall',
        'list_expr' => '\Permify\Model\CreateList',
        'struct_expr' => '\Permify\Model\CreateStruct',
        'comprehension_expr' => '\Permify\Model\Comprehension'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int64',
        'const_expr' => null,
        'ident_expr' => null,
        'select_expr' => null,
        'call_expr' => null,
        'list_expr' => null,
        'struct_expr' => null,
        'comprehension_expr' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'const_expr' => false,
        'ident_expr' => false,
        'select_expr' => false,
        'call_expr' => false,
        'list_expr' => false,
        'struct_expr' => false,
        'comprehension_expr' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'const_expr' => 'constExpr',
        'ident_expr' => 'identExpr',
        'select_expr' => 'selectExpr',
        'call_expr' => 'callExpr',
        'list_expr' => 'listExpr',
        'struct_expr' => 'structExpr',
        'comprehension_expr' => 'comprehensionExpr'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'const_expr' => 'setConstExpr',
        'ident_expr' => 'setIdentExpr',
        'select_expr' => 'setSelectExpr',
        'call_expr' => 'setCallExpr',
        'list_expr' => 'setListExpr',
        'struct_expr' => 'setStructExpr',
        'comprehension_expr' => 'setComprehensionExpr'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'const_expr' => 'getConstExpr',
        'ident_expr' => 'getIdentExpr',
        'select_expr' => 'getSelectExpr',
        'call_expr' => 'getCallExpr',
        'list_expr' => 'getListExpr',
        'struct_expr' => 'getStructExpr',
        'comprehension_expr' => 'getComprehensionExpr'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('const_expr', $data ?? [], null);
        $this->setIfExists('ident_expr', $data ?? [], null);
        $this->setIfExists('select_expr', $data ?? [], null);
        $this->setIfExists('call_expr', $data ?? [], null);
        $this->setIfExists('list_expr', $data ?? [], null);
        $this->setIfExists('struct_expr', $data ?? [], null);
        $this->setIfExists('comprehension_expr', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id Required. An id assigned to this node by the parser which is unique in a given expression tree. This is used to associate type information and other attributes to a node in the parse tree.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets const_expr
     *
     * @return \Permify\Model\Constant|null
     */
    public function getConstExpr()
    {
        return $this->container['const_expr'];
    }

    /**
     * Sets const_expr
     *
     * @param \Permify\Model\Constant|null $const_expr const_expr
     *
     * @return self
     */
    public function setConstExpr($const_expr)
    {
        if (is_null($const_expr)) {
            throw new \InvalidArgumentException('non-nullable const_expr cannot be null');
        }
        $this->container['const_expr'] = $const_expr;

        return $this;
    }

    /**
     * Gets ident_expr
     *
     * @return \Permify\Model\Ident|null
     */
    public function getIdentExpr()
    {
        return $this->container['ident_expr'];
    }

    /**
     * Sets ident_expr
     *
     * @param \Permify\Model\Ident|null $ident_expr ident_expr
     *
     * @return self
     */
    public function setIdentExpr($ident_expr)
    {
        if (is_null($ident_expr)) {
            throw new \InvalidArgumentException('non-nullable ident_expr cannot be null');
        }
        $this->container['ident_expr'] = $ident_expr;

        return $this;
    }

    /**
     * Gets select_expr
     *
     * @return \Permify\Model\Select|null
     */
    public function getSelectExpr()
    {
        return $this->container['select_expr'];
    }

    /**
     * Sets select_expr
     *
     * @param \Permify\Model\Select|null $select_expr select_expr
     *
     * @return self
     */
    public function setSelectExpr($select_expr)
    {
        if (is_null($select_expr)) {
            throw new \InvalidArgumentException('non-nullable select_expr cannot be null');
        }
        $this->container['select_expr'] = $select_expr;

        return $this;
    }

    /**
     * Gets call_expr
     *
     * @return \Permify\Model\ExprCall|null
     */
    public function getCallExpr()
    {
        return $this->container['call_expr'];
    }

    /**
     * Sets call_expr
     *
     * @param \Permify\Model\ExprCall|null $call_expr call_expr
     *
     * @return self
     */
    public function setCallExpr($call_expr)
    {
        if (is_null($call_expr)) {
            throw new \InvalidArgumentException('non-nullable call_expr cannot be null');
        }
        $this->container['call_expr'] = $call_expr;

        return $this;
    }

    /**
     * Gets list_expr
     *
     * @return \Permify\Model\CreateList|null
     */
    public function getListExpr()
    {
        return $this->container['list_expr'];
    }

    /**
     * Sets list_expr
     *
     * @param \Permify\Model\CreateList|null $list_expr list_expr
     *
     * @return self
     */
    public function setListExpr($list_expr)
    {
        if (is_null($list_expr)) {
            throw new \InvalidArgumentException('non-nullable list_expr cannot be null');
        }
        $this->container['list_expr'] = $list_expr;

        return $this;
    }

    /**
     * Gets struct_expr
     *
     * @return \Permify\Model\CreateStruct|null
     */
    public function getStructExpr()
    {
        return $this->container['struct_expr'];
    }

    /**
     * Sets struct_expr
     *
     * @param \Permify\Model\CreateStruct|null $struct_expr struct_expr
     *
     * @return self
     */
    public function setStructExpr($struct_expr)
    {
        if (is_null($struct_expr)) {
            throw new \InvalidArgumentException('non-nullable struct_expr cannot be null');
        }
        $this->container['struct_expr'] = $struct_expr;

        return $this;
    }

    /**
     * Gets comprehension_expr
     *
     * @return \Permify\Model\Comprehension|null
     */
    public function getComprehensionExpr()
    {
        return $this->container['comprehension_expr'];
    }

    /**
     * Sets comprehension_expr
     *
     * @param \Permify\Model\Comprehension|null $comprehension_expr comprehension_expr
     *
     * @return self
     */
    public function setComprehensionExpr($comprehension_expr)
    {
        if (is_null($comprehension_expr)) {
            throw new \InvalidArgumentException('non-nullable comprehension_expr cannot be null');
        }
        $this->container['comprehension_expr'] = $comprehension_expr;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


