<?php
/**
 * V1alpha1Type
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Permify API
 *
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.5.4
 * Contact: hello@permify.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Permify\Model;

use \ArrayAccess;
use \Permify\ObjectSerializer;

/**
 * V1alpha1Type Class Doc Comment
 *
 * @category Class
 * @description Represents a CEL type.
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V1alpha1Type implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'v1alpha1.Type';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'dyn' => 'object',
        'null' => 'string',
        'primitive' => '\Permify\Model\PrimitiveType',
        'wrapper' => '\Permify\Model\PrimitiveType',
        'well_known' => '\Permify\Model\WellKnownType',
        'list_type' => '\Permify\Model\ListType',
        'map_type' => '\Permify\Model\MapType',
        'function' => '\Permify\Model\FunctionType',
        'message_type' => 'string',
        'type_param' => 'string',
        'type' => '\Permify\Model\V1alpha1Type',
        'error' => 'object',
        'abstract_type' => '\Permify\Model\AbstractType'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'dyn' => null,
        'null' => null,
        'primitive' => null,
        'wrapper' => null,
        'well_known' => null,
        'list_type' => null,
        'map_type' => null,
        'function' => null,
        'message_type' => null,
        'type_param' => null,
        'type' => null,
        'error' => null,
        'abstract_type' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'dyn' => false,
        'null' => false,
        'primitive' => false,
        'wrapper' => false,
        'well_known' => false,
        'list_type' => false,
        'map_type' => false,
        'function' => false,
        'message_type' => false,
        'type_param' => false,
        'type' => false,
        'error' => false,
        'abstract_type' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'dyn' => 'dyn',
        'null' => 'null',
        'primitive' => 'primitive',
        'wrapper' => 'wrapper',
        'well_known' => 'wellKnown',
        'list_type' => 'listType',
        'map_type' => 'mapType',
        'function' => 'function',
        'message_type' => 'messageType',
        'type_param' => 'typeParam',
        'type' => 'type',
        'error' => 'error',
        'abstract_type' => 'abstractType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'dyn' => 'setDyn',
        'null' => 'setNull',
        'primitive' => 'setPrimitive',
        'wrapper' => 'setWrapper',
        'well_known' => 'setWellKnown',
        'list_type' => 'setListType',
        'map_type' => 'setMapType',
        'function' => 'setFunction',
        'message_type' => 'setMessageType',
        'type_param' => 'setTypeParam',
        'type' => 'setType',
        'error' => 'setError',
        'abstract_type' => 'setAbstractType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'dyn' => 'getDyn',
        'null' => 'getNull',
        'primitive' => 'getPrimitive',
        'wrapper' => 'getWrapper',
        'well_known' => 'getWellKnown',
        'list_type' => 'getListType',
        'map_type' => 'getMapType',
        'function' => 'getFunction',
        'message_type' => 'getMessageType',
        'type_param' => 'getTypeParam',
        'type' => 'getType',
        'error' => 'getError',
        'abstract_type' => 'getAbstractType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('dyn', $data ?? [], null);
        $this->setIfExists('null', $data ?? [], null);
        $this->setIfExists('primitive', $data ?? [], null);
        $this->setIfExists('wrapper', $data ?? [], null);
        $this->setIfExists('well_known', $data ?? [], null);
        $this->setIfExists('list_type', $data ?? [], null);
        $this->setIfExists('map_type', $data ?? [], null);
        $this->setIfExists('function', $data ?? [], null);
        $this->setIfExists('message_type', $data ?? [], null);
        $this->setIfExists('type_param', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('error', $data ?? [], null);
        $this->setIfExists('abstract_type', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets dyn
     *
     * @return object|null
     */
    public function getDyn()
    {
        return $this->container['dyn'];
    }

    /**
     * Sets dyn
     *
     * @param object|null $dyn Dynamic type.
     *
     * @return self
     */
    public function setDyn($dyn)
    {
        if (is_null($dyn)) {
            throw new \InvalidArgumentException('non-nullable dyn cannot be null');
        }
        $this->container['dyn'] = $dyn;

        return $this;
    }

    /**
     * Gets null
     *
     * @return string|null
     */
    public function getNull()
    {
        return $this->container['null'];
    }

    /**
     * Sets null
     *
     * @param string|null $null Null value.
     *
     * @return self
     */
    public function setNull($null)
    {
        if (is_null($null)) {
            throw new \InvalidArgumentException('non-nullable null cannot be null');
        }
        $this->container['null'] = $null;

        return $this;
    }

    /**
     * Gets primitive
     *
     * @return \Permify\Model\PrimitiveType|null
     */
    public function getPrimitive()
    {
        return $this->container['primitive'];
    }

    /**
     * Sets primitive
     *
     * @param \Permify\Model\PrimitiveType|null $primitive primitive
     *
     * @return self
     */
    public function setPrimitive($primitive)
    {
        if (is_null($primitive)) {
            throw new \InvalidArgumentException('non-nullable primitive cannot be null');
        }
        $this->container['primitive'] = $primitive;

        return $this;
    }

    /**
     * Gets wrapper
     *
     * @return \Permify\Model\PrimitiveType|null
     */
    public function getWrapper()
    {
        return $this->container['wrapper'];
    }

    /**
     * Sets wrapper
     *
     * @param \Permify\Model\PrimitiveType|null $wrapper wrapper
     *
     * @return self
     */
    public function setWrapper($wrapper)
    {
        if (is_null($wrapper)) {
            throw new \InvalidArgumentException('non-nullable wrapper cannot be null');
        }
        $this->container['wrapper'] = $wrapper;

        return $this;
    }

    /**
     * Gets well_known
     *
     * @return \Permify\Model\WellKnownType|null
     */
    public function getWellKnown()
    {
        return $this->container['well_known'];
    }

    /**
     * Sets well_known
     *
     * @param \Permify\Model\WellKnownType|null $well_known well_known
     *
     * @return self
     */
    public function setWellKnown($well_known)
    {
        if (is_null($well_known)) {
            throw new \InvalidArgumentException('non-nullable well_known cannot be null');
        }
        $this->container['well_known'] = $well_known;

        return $this;
    }

    /**
     * Gets list_type
     *
     * @return \Permify\Model\ListType|null
     */
    public function getListType()
    {
        return $this->container['list_type'];
    }

    /**
     * Sets list_type
     *
     * @param \Permify\Model\ListType|null $list_type list_type
     *
     * @return self
     */
    public function setListType($list_type)
    {
        if (is_null($list_type)) {
            throw new \InvalidArgumentException('non-nullable list_type cannot be null');
        }
        $this->container['list_type'] = $list_type;

        return $this;
    }

    /**
     * Gets map_type
     *
     * @return \Permify\Model\MapType|null
     */
    public function getMapType()
    {
        return $this->container['map_type'];
    }

    /**
     * Sets map_type
     *
     * @param \Permify\Model\MapType|null $map_type map_type
     *
     * @return self
     */
    public function setMapType($map_type)
    {
        if (is_null($map_type)) {
            throw new \InvalidArgumentException('non-nullable map_type cannot be null');
        }
        $this->container['map_type'] = $map_type;

        return $this;
    }

    /**
     * Gets function
     *
     * @return \Permify\Model\FunctionType|null
     */
    public function getFunction()
    {
        return $this->container['function'];
    }

    /**
     * Sets function
     *
     * @param \Permify\Model\FunctionType|null $function function
     *
     * @return self
     */
    public function setFunction($function)
    {
        if (is_null($function)) {
            throw new \InvalidArgumentException('non-nullable function cannot be null');
        }
        $this->container['function'] = $function;

        return $this;
    }

    /**
     * Gets message_type
     *
     * @return string|null
     */
    public function getMessageType()
    {
        return $this->container['message_type'];
    }

    /**
     * Sets message_type
     *
     * @param string|null $message_type Protocol buffer message type.  The `message_type` string specifies the qualified message type name. For example, `google.plus.Profile`.
     *
     * @return self
     */
    public function setMessageType($message_type)
    {
        if (is_null($message_type)) {
            throw new \InvalidArgumentException('non-nullable message_type cannot be null');
        }
        $this->container['message_type'] = $message_type;

        return $this;
    }

    /**
     * Gets type_param
     *
     * @return string|null
     */
    public function getTypeParam()
    {
        return $this->container['type_param'];
    }

    /**
     * Sets type_param
     *
     * @param string|null $type_param Type param type.  The `type_param` string specifies the type parameter name, e.g. `list<E>` would be a `list_type` whose element type was a `type_param` type named `E`.
     *
     * @return self
     */
    public function setTypeParam($type_param)
    {
        if (is_null($type_param)) {
            throw new \InvalidArgumentException('non-nullable type_param cannot be null');
        }
        $this->container['type_param'] = $type_param;

        return $this;
    }

    /**
     * Gets type
     *
     * @return \Permify\Model\V1alpha1Type|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \Permify\Model\V1alpha1Type|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets error
     *
     * @return object|null
     */
    public function getError()
    {
        return $this->container['error'];
    }

    /**
     * Sets error
     *
     * @param object|null $error Error type.  During type-checking if an expression is an error, its type is propagated as the `ERROR` type. This permits the type-checker to discover other errors present in the expression.
     *
     * @return self
     */
    public function setError($error)
    {
        if (is_null($error)) {
            throw new \InvalidArgumentException('non-nullable error cannot be null');
        }
        $this->container['error'] = $error;

        return $this;
    }

    /**
     * Gets abstract_type
     *
     * @return \Permify\Model\AbstractType|null
     */
    public function getAbstractType()
    {
        return $this->container['abstract_type'];
    }

    /**
     * Sets abstract_type
     *
     * @param \Permify\Model\AbstractType|null $abstract_type abstract_type
     *
     * @return self
     */
    public function setAbstractType($abstract_type)
    {
        if (is_null($abstract_type)) {
            throw new \InvalidArgumentException('non-nullable abstract_type cannot be null');
        }
        $this->container['abstract_type'] = $abstract_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


