<?php
/**
 * V1Operation
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Permify API
 *
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.5.4
 * Contact: hello@permify.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Permify\Model;

use \ArrayAccess;
use \Permify\ObjectSerializer;

/**
 * V1Operation Class Doc Comment
 *
 * @category Class
 * @description Operation is a message representing a series of operations that can be performed. It includes fields for writing and deleting relationships and attributes.
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V1Operation implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'v1.Operation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'relationships_write' => 'string[]',
        'relationships_delete' => 'string[]',
        'attributes_write' => 'string[]',
        'attributes_delete' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'relationships_write' => null,
        'relationships_delete' => null,
        'attributes_write' => null,
        'attributes_delete' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'relationships_write' => false,
        'relationships_delete' => false,
        'attributes_write' => false,
        'attributes_delete' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'relationships_write' => 'relationships_write',
        'relationships_delete' => 'relationships_delete',
        'attributes_write' => 'attributes_write',
        'attributes_delete' => 'attributes_delete'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'relationships_write' => 'setRelationshipsWrite',
        'relationships_delete' => 'setRelationshipsDelete',
        'attributes_write' => 'setAttributesWrite',
        'attributes_delete' => 'setAttributesDelete'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'relationships_write' => 'getRelationshipsWrite',
        'relationships_delete' => 'getRelationshipsDelete',
        'attributes_write' => 'getAttributesWrite',
        'attributes_delete' => 'getAttributesDelete'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('relationships_write', $data ?? [], null);
        $this->setIfExists('relationships_delete', $data ?? [], null);
        $this->setIfExists('attributes_write', $data ?? [], null);
        $this->setIfExists('attributes_delete', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets relationships_write
     *
     * @return string[]|null
     */
    public function getRelationshipsWrite()
    {
        return $this->container['relationships_write'];
    }

    /**
     * Sets relationships_write
     *
     * @param string[]|null $relationships_write 'relationships_write' is a repeated string field for storing relationship keys that are to be written or created.
     *
     * @return self
     */
    public function setRelationshipsWrite($relationships_write)
    {
        if (is_null($relationships_write)) {
            throw new \InvalidArgumentException('non-nullable relationships_write cannot be null');
        }
        $this->container['relationships_write'] = $relationships_write;

        return $this;
    }

    /**
     * Gets relationships_delete
     *
     * @return string[]|null
     */
    public function getRelationshipsDelete()
    {
        return $this->container['relationships_delete'];
    }

    /**
     * Sets relationships_delete
     *
     * @param string[]|null $relationships_delete 'relationships_delete' is a repeated string field for storing relationship keys that are to be deleted or removed.
     *
     * @return self
     */
    public function setRelationshipsDelete($relationships_delete)
    {
        if (is_null($relationships_delete)) {
            throw new \InvalidArgumentException('non-nullable relationships_delete cannot be null');
        }
        $this->container['relationships_delete'] = $relationships_delete;

        return $this;
    }

    /**
     * Gets attributes_write
     *
     * @return string[]|null
     */
    public function getAttributesWrite()
    {
        return $this->container['attributes_write'];
    }

    /**
     * Sets attributes_write
     *
     * @param string[]|null $attributes_write 'attributes_write' is a repeated string field for storing attribute keys that are to be written or created.
     *
     * @return self
     */
    public function setAttributesWrite($attributes_write)
    {
        if (is_null($attributes_write)) {
            throw new \InvalidArgumentException('non-nullable attributes_write cannot be null');
        }
        $this->container['attributes_write'] = $attributes_write;

        return $this;
    }

    /**
     * Gets attributes_delete
     *
     * @return string[]|null
     */
    public function getAttributesDelete()
    {
        return $this->container['attributes_delete'];
    }

    /**
     * Sets attributes_delete
     *
     * @param string[]|null $attributes_delete 'attributes_delete' is a repeated string field for storing attribute keys that are to be deleted or removed.
     *
     * @return self
     */
    public function setAttributesDelete($attributes_delete)
    {
        if (is_null($attributes_delete)) {
            throw new \InvalidArgumentException('non-nullable attributes_delete cannot be null');
        }
        $this->container['attributes_delete'] = $attributes_delete;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


