<?php
/**
 * AttributeTypeTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Permify API
 *
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.5.4
 * Contact: hello@permify.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Permify\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AttributeTypeTest Class Doc Comment
 *
 * @category    Class
 * @description Enumerates the types of attribute.   - ATTRIBUTE_TYPE_BOOLEAN: A boolean attribute type.  - ATTRIBUTE_TYPE_BOOLEAN_ARRAY: A boolean array attribute type.  - ATTRIBUTE_TYPE_STRING: A string attribute type.  - ATTRIBUTE_TYPE_STRING_ARRAY: A string array attribute type.  - ATTRIBUTE_TYPE_INTEGER: An integer attribute type.  - ATTRIBUTE_TYPE_INTEGER_ARRAY: An integer array attribute type.  - ATTRIBUTE_TYPE_DOUBLE: A double attribute type.  - ATTRIBUTE_TYPE_DOUBLE_ARRAY: A double array attribute type.
 * @package     Permify
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AttributeTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AttributeType"
     */
    public function testAttributeType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
