<?php
/**
 * ConstantTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Permify API
 *
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.5.4
 * Contact: hello@permify.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Permify\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ConstantTest Class Doc Comment
 *
 * @category    Class
 * @description Represents a primitive literal.  Named &#39;Constant&#39; here for backwards compatibility.  This is similar as the primitives supported in the well-known type &#x60;google.protobuf.Value&#x60;, but richer so it can represent CEL&#39;s full range of primitives.  Lists and structs are not included as constants as these aggregate types may contain [Expr][google.api.expr.v1alpha1.Expr] elements which require evaluation and are thus not constant.  Examples of literals include: &#x60;\&quot;hello\&quot;&#x60;, &#x60;b&#39;bytes&#39;&#x60;, &#x60;1u&#x60;, &#x60;4.2&#x60;, &#x60;-2&#x60;, &#x60;true&#x60;, &#x60;null&#x60;.
 * @package     Permify
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ConstantTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Constant"
     */
    public function testConstant()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "null_value"
     */
    public function testPropertyNullValue()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bool_value"
     */
    public function testPropertyBoolValue()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "int64_value"
     */
    public function testPropertyInt64Value()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "uint64_value"
     */
    public function testPropertyUint64Value()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "double_value"
     */
    public function testPropertyDoubleValue()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "string_value"
     */
    public function testPropertyStringValue()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bytes_value"
     */
    public function testPropertyBytesValue()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "duration_value"
     */
    public function testPropertyDurationValue()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "timestamp_value"
     */
    public function testPropertyTimestampValue()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
