<?php
/**
 * PrimitiveTypeTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Permify API
 *
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.5.4
 * Contact: hello@permify.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Permify\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PrimitiveTypeTest Class Doc Comment
 *
 * @category    Class
 * @description CEL primitive types.   - BOOL: Boolean type.  - INT64: Int64 type.  Proto-based integer values are widened to int64.  - UINT64: Uint64 type.  Proto-based unsigned integer values are widened to uint64.  - DOUBLE: Double type.  Proto-based float values are widened to double values.  - STRING: String type.  - BYTES: Bytes type.
 * @package     Permify
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PrimitiveTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PrimitiveType"
     */
    public function testPrimitiveType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
