<?php
/**
 * V1alpha1TypeTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Permify API
 *
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.5.4
 * Contact: hello@permify.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Permify\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * V1alpha1TypeTest Class Doc Comment
 *
 * @category    Class
 * @description Represents a CEL type.
 * @package     Permify
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class V1alpha1TypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "V1alpha1Type"
     */
    public function testV1alpha1Type()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dyn"
     */
    public function testPropertyDyn()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "null"
     */
    public function testPropertyNull()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "primitive"
     */
    public function testPropertyPrimitive()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "wrapper"
     */
    public function testPropertyWrapper()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "well_known"
     */
    public function testPropertyWellKnown()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "list_type"
     */
    public function testPropertyListType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "map_type"
     */
    public function testPropertyMapType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "function"
     */
    public function testPropertyFunction()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "message_type"
     */
    public function testPropertyMessageType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "type_param"
     */
    public function testPropertyTypeParam()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "abstract_type"
     */
    public function testPropertyAbstractType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
