<?php
/**
 * WellKnownTypeTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Permify API
 *
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.5.4
 * Contact: hello@permify.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Permify\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * WellKnownTypeTest Class Doc Comment
 *
 * @category    Class
 * @description Well-known protobuf types treated with first-class support in CEL.   - ANY: Well-known protobuf.Any type.  Any types are a polymorphic message type. During type-checking they are treated like &#x60;DYN&#x60; types, but at runtime they are resolved to a specific message type specified at evaluation time.  - TIMESTAMP: Well-known protobuf.Timestamp type, internally referenced as &#x60;timestamp&#x60;.  - DURATION: Well-known protobuf.Duration type, internally referenced as &#x60;duration&#x60;.
 * @package     Permify
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class WellKnownTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "WellKnownType"
     */
    public function testWellKnownType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
