<?php
/**
 * DataApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Permify API
 *
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.5.4
 * Contact: hello@permify.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Permify\Test\Api;

use \Permify\Configuration;
use \Permify\ApiException;
use \Permify\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DataApiTest Class Doc Comment
 *
 * @category Class
 * @package  Permify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DataApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for bundleRun
     *
     * run bundle.
     *
     */
    public function testBundleRun()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataAttributesRead
     *
     * read attributes.
     *
     */
    public function testDataAttributesRead()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataDelete
     *
     * delete data.
     *
     */
    public function testDataDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataRelationshipsRead
     *
     * read relationships.
     *
     */
    public function testDataRelationshipsRead()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataWrite
     *
     * write data.
     *
     */
    public function testDataWrite()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for relationshipsDelete
     *
     * delete relationships.
     *
     */
    public function testRelationshipsDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for relationshipsWrite
     *
     * write relationships.
     *
     */
    public function testRelationshipsWrite()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
